// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORMIntro.Models;

namespace ORMIntro.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20210812161114_AddSauce")]
    partial class AddSauce
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ORMIntro.Models.Sundae", b =>
                {
                    b.Property<int>("SundaeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Flavor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sauce")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Scoops")
                        .HasColumnType("int");

                    b.Property<string>("Topping")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SundaeId");

                    b.ToTable("Sundaes");
                });
#pragma warning restore 612, 618
        }
    }
}
